### PR TITLE
Toggle visibility: Add option input for tabindex value

### PR DESCRIPTION
**Pull request by msenosiain**
Added an input so one can set the tabindex for the button as requested in #255

### CODE REVIEW

**Comment by AnthonyNahas** [comment]
@msenosiain thanks for contributing.

Why do we need the tabIndex attribute ?

May you update please as well the api table in the readme ?


thank you

**Comment by msenosiain** [comment]
> @msenosiain thanks for contributing.
> 
> Why do we need the tabIndex attribute ?
> 
> May you update please as well the api table in the readme ?
> 
> thank you

We need it because if you are using just the keyboard for filling the form whenever you hit <tab> inside the password field the focus goes to the toggle visibility button instead of going to the confirm password field. By allowing to set the tabindex attribute you can avoid that behavior for the toggle visibility button.

Will update the readme no problem

**Comment by AnthonyNahas** [comment]
@msenosiain may you adapt this PR to the latest version of this lib in order to merge it soon ?

**Comment by msenosiain** [comment]
> @msenosiain may you adapt this PR to the latest version of this lib in order to merge it soon ?

All conflicts solved

**Pull request merged**
